export default [
  '3D printing',
  'Acroyoga',
  'Art',
  'Astrology',
  'Astronomy',
  'Baking',
  'Bartending',
  'Beatboxing',
  'Beer tasting',
  'Blogging',
  'Bonsai',
  'Board games',
  'Book clubs',
  'Bowling',
  'Breadmaking',
  'Building',
  'Calligraphy',
  'Candle making',
  'Candy making',
  'Car building',
  'Card games',
  'Cardistry',
  'Ceramics',
  'Chess',
  'Clothesmaking',
  'Coffee roasting',
  'Computer programming',
  'Cooking',
  'Cosplaying',
  'Crafting',
  'Creative writing',
  'Crocheting',
  'Cross-stitch',
  'Dance',
  'Decorating',
  'Digital arts',
  'Diving',
  'DJing',
  'Drawing',
  'Embroidery',
  'Engraving',
  'Escape rooms',
  'Fashion design',
  'Filmmaking',
  'Fire breathing',
  'Fire spinning',
  'Fire manipulation',
  'Flow arts',
  'Flower arranging',
  'Furniture building',
  'Gaming',
  'Glassblowing',
  'Gardening',
  'Graphic design',
  'Houseplants',
  'Hula hooping',
  'Hydroponics',
  'Ice skating',
  'Improv',
  'Jewelry making',
  'Jigsaw puzzles',
  'Journaling',
  'Judo',
  'Juggling',
  'Karaoke',
  'Karate',
  'Kendama',
  'Knife making',
  'Knitting',
  'Lapidary',
  'Leather crafting',
  'Machining',
  'Macrame',
  'Makeup',
  'Meditation',
  'Metalworking',
  'Model building',
  'Modeling',
  'Modular synthesizers',
  'Music',
  'Needlepoint',
  'Origami',
  'Painting',
  'Performance art',
  'Photography',
  'Pilates',
  'Playing musical instruments',
  'Poetry',
  'Poi',
  'Pole dancing',
  'Puzzles',
  'Pyrotechnics',
  'Quilting',
  'Rapping',
  'Recipe creation',
  'Refinishing',
  'Reiki',
  'Rock climbing',
  'Scrapbooking',
  'Scuba Diving',
  'Sculpting',
  'Shibari',
  'Sewing',
  'Singing',
  'Skating',
  'Sketching',
  'Soapmaking',
  'Storytelling',
  'Sudoku',
  'Taekwondo',
  'Tarot',
  'Tattooing',
  'Thrifting',
  'Upcycling',
  'Video gaming',
  'VR Gaming',
  'Weaving',
  'Weight training',
  'Welding',
  'Wine tasting',
  'Winemaking',
  'Witchcraft',
  'Woodworking',
  'Writing',
  'Writing music',
  'Yo-yo',
  'Yoga',
  'Zumba',
]
